### ISSUE TITLE
The mod doesnt work

### ISSUE THREAD

**Issue by B14nk2** [absolutelyaya/Goop#5]
Either the mod is just a pure api that adds nothing and the slime/blood effects that are shown on the mod page are not actually a part of this mod, (if thats the case i think that should be stated on the mod page) or the mod is broken. It might be just my stupid ass but the mod doesnt work at all theres no slime effects and no blood effects nothin.

Also the mod crashes without cloth config api for some reason even tho its supposed to be optional as stated on the mod page.

i tried all the versions of the goop mod and the results were the same, maybe its not compatible with some fabric versions? idk.

**Comment by absolutelyaya** [comment]
Changed the cloth config from optional to required on the download pages
The is mainly a Library, has some example emitters by itself though. You need to enable dev emitters in your Settings. The example emitters are Slimes leaving behind puddles when jumping and taking damage, Blood from Zombies, Snow Golems turning into a puddle when dying and thrown eggs leaving behind a splatter thingie when hitting a Block
It does say on the download pages that the mod doesn't do much by itself, so I dunno what you were expecting

**Comment by B14nk2** [comment]
I was kinda expecting the things that were shown on the mod page to answer your question.

Everything is cool but like, why do you have to enable the dev emitters option for all the features to start working? I dont really get that, wouldnt it just cause confusion?

**Comment by absolutelyaya** [comment]
Those aren't really features, they're just examples of how the library could be used. When other devs use it to add their own effects, these example emitters and theirs would both be active and could cause unwanted effects, which is why they're disabled by default. As long as others don't explicitly mark their emitters as dev emitters, they will always be active
