### ISSUE TITLE
Not Working For Version 1.20.1 Fabric

### ISSUE THREAD

**Issue by cosmichero2025** [absolutelyaya/Goop#7]
I'm using the most recent version posted on Feb 18th for fabric. It seems that none of the effects are working but the mod is on actively. I've tried disabling to find the mod that is causing the conflict but I seem to not be able to figure out if its a single mod or a combination off two others that's causing the issue. My modlist below

	Fabric API
	Yeetus Experimentus
	NarrusYeetus
	Sodium
	Sodium Extra
	Lithium
	Indium
	Dynamic FPS
	Enhanced Block Entities
	EntityCulling
	FastQuit
	FerriteCore
	ImmediatelyFast
	Language Reload
	Memory Leak Fix
	ModernFix
	Fadeless
	Cull Less Leaves
	Fabrishot
	More Culling
	Model Gap Fix
	AntiGhost
	Cubes Without Borders
	No Chat Reports
	Debugify
	MixinTrace
	Not Enough Crashes
	Better Beds
	Concurrent Chunk Management Engine (Fabric)
	Noisium
	ThreadTweak
	Server Sleep
	No Telemetry
	Neruina - Ticking Entity Fixer
	Every Compat (Wood Good)
	Polymorph
	Mod Menu
	Clean F3
	Paginated Advancements & Custom Frames
	Better Mount HUD 
	ToolTipFix
	Your Options Shall Be Respected 
	Reese's Sodium Options
	Jade
	Jade Addons
	EMI
	Mouse Tweaks
	InvMove 
	Traveler's Titles 
	Raised
	Pick Up Notifier
	Better Ping Display 
	Dark Loading Screen
	DarkTitleBar
	Dark Mode Everywhere
	Tips
	Cut Through
	AmbientSounds
	Presence Footsteps
	Drip Sounds
	Sounds
	Sound Physics Remastered
	ImmersiveThunder
	Particular ✨
	Visuality
	Goop
	Time & Wind
	FootprintParticle 
	This Rocks!
	SleepWarp
	Explosive Enhancement
	Visual Overhaul
	Visual Workbench
	Wakes

**Comment by Ferrlius** [comment]
yeah I see the same effect. I mean no effects, although I have no mods except Goop, Fabric API and Cloth Config API
so it's 100% Goop issue. and the mod actually is fire, please fix it

**Comment by Ferrlius** [comment]
weird that none of the published mod versions on fabric 1.20.1 create any effect. Am I doing anything wrong?

**Comment by absolutelyaya** [comment]
oh didn't notice this issue being opened
refer to #5
